language: node_js

node_js:
- '11'

cache:
  directories: node_modules

before_script:
- yarn build

deploy:
  provider: heroku
  api_key:
    secure: "secure-key"
  app: credere-test
  on:
    repo: wellitongervickas/credere-test
