language: node_js

node_js:
- '11'

cache:
  directories: node_modules

before_script:
- yarn build

deploy:
  provider: heroku
  api_key:
    secure: "d7c89526-d511-4cc2-86cf-b0fe27d12e74"
  app: credere-test
  on:
    repo: wellitongervickas/credere-test
