language: node_js

node_js:
- '11'

cache:
  directories: node_modules

before_script:
- yarn build

after_success:
- yarn test:coverage

deploy:
  provider: heroku
  api_key:
    secure: "d9263ec2-43c1-499b-a412-43fcd25f2101"
  app: credere-test
